appium/io.appium.settings

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/appium/settings/Unlock.java
Addresses https://github.com/appium/appium/issues/6089
> Port unlock functionality to settings helper

- NOTICE.txt
- README.md
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/appium/settings/AppiumIME.java
- app/src/main/java/io/appium/settings/UnicodeIME.java
This will allow to save time for session init by having all helpers in a single apk
> Port UnicodeIME helper into the current package

- .travis.yml
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/appium/settings/handlers/AnimationSettingHandler.java
- app/src/main/java/io/appium/settings/handlers/DataConnectionSettingHandler.java
- package.json
- Added `./gradlew lint` in CI
- Fixed errors by the lint
> add android lint, fix errors

- app/src/main/java/io/appium/settings/Settings.java
- app/src/main/java/io/appium/settings/receivers/AnimationSettingReceiver.java
- app/src/main/java/io/appium/settings/receivers/DataConnectionSettingReceiver.java
- app/src/main/java/io/appium/settings/receivers/HasAction.java
- app/src/main/java/io/appium/settings/receivers/LocaleSettingReceiver.java
- app/src/main/java/io/appium/settings/receivers/LocationInfoReceiver.java
I observe some unnecessary repetition in the current code. We need to get rid of it
> Refactor broadcast receivers registration

- app/src/main/java/io/appium/settings/LocationTracker.java
- app/src/main/java/io/appium/settings/Settings.java
- app/src/main/java/io/appium/settings/receivers/LocationInfoReceiver.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Addresses https://github.com/appium/io.appium.settings/issues/34
@dmissmann Can you please review the fix?
> Add verification of location tracker state

- app/src/main/java/io/appium/settings/LocationTracker.java
- app/src/main/java/io/appium/settings/Settings.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Hopefully addresses https://github.com/appium/appium/issues/12734
> Avoid unexpected Google Location API crashes

- README.md
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/appium/settings/Settings.java
- app/src/main/java/io/appium/settings/handlers/BluetoothConnectionSettingHandler.java
- app/src/main/java/io/appium/settings/receivers/AbstractSettingReceiver.java
- app/src/main/java/io/appium/settings/receivers/BluetoothConnectionSettingReceiver.java
- app/src/main/java/io/appium/settings/receivers/UnpairBluetoothDevicesReceiver.java
Added receivers for:
- handling Android Bluetooth adapter state
- unpairing all bonded Bluetooth devices
> Bluetooth handling

- README.md
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/appium/settings/Settings.java
- app/src/main/java/io/appium/settings/receivers/SmsReader.java
https://github.com/appium/appium-uiautomator2-server/issues/333
> feat: Add a possibility to read incoming SMS messages

- .github/workflows/gradle-wrapper-validation.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
* Android Studio 3.6.3
* Gradle 6.4.1
* Github action to verify wrapper
> Android Studio 3.6.3

- app/src/main/java/io/appium/settings/receivers/SmsReader.java
https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=14217&view=logs&j=ec425b7f-ae8e-572f-7322-15a89568ac3d&t=bb07fc4b-855c-5373-be1b-608df755cc9e
> fix: Address linter issue

- .azure-pipelines.yml
- .azure-templates/gradle_job.yml
- README.md
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/appium/settings/Settings.java
- app/src/main/java/io/appium/settings/receivers/MediaScannerReceiver.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Related to https://github.com/appium/appium/issues/16184
> feat: Add media scanner broadcast handler

- .azure-templates/gradle_job.yml
I create PR for test build on CI
to fix #79
> ci: add copy and publish steps

- app/src/main/java/io/appium/settings/receivers/LocaleSettingReceiver.java
Related to https://github.com/appium/appium/issues/17171
> chore: Update locale selection procedure if no matches were found for it

- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/publish.js.yml
- app/build.gradle
- app/src/main/AndroidManifest.xml
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
Also added the dependabot rule for maven dependencies
> chore: Bump Gradle version

- lib/client.js
Similar to https://github.com/appium/appium-adb/pull/715
> fix: Update process existence check

- package.json
- test/unit/client-specs.js
Add tests used added in https://github.com/appium/appium-adb/pull/715/files
> test: add tests for foreground check

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
instead of https://github.com/appium/io.appium.settings/pull/152
> chore(deps): bump com.android.tools.build:gradle from 8.2.2 to 8.3.0

- app/src/main/java/io/appium/settings/handlers/AbstractSettingHandler.java
- app/src/main/java/io/appium/settings/handlers/BluetoothConnectionSettingHandler.java
- app/src/main/java/io/appium/settings/receivers/BluetoothConnectionSettingReceiver.java
- lib/client.js
- lib/commands/animation.js
- lib/commands/bluetooth.js
- lib/commands/clipboard.js
- lib/commands/geolocation.js
- lib/commands/locale.js
- lib/commands/media.js
- lib/commands/network.js
- lib/commands/notifications.js
- lib/commands/sms.js
- lib/commands/typing.js
- lib/commands/utf7.js
- lib/constants.js
Also improved the result validation for APis that perform broadcasting
> feat: Add helpers for dealing with bluetooth

- README.md
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/appium/settings/Settings.java
- app/src/main/java/io/appium/settings/receivers/LocalesReader.java
- lib/client.js
- lib/commands/locale.js
- lib/constants.js
This should help to provide more helpful message for locale change failures
> feat: Add an API to list locales supported by the device

- README.md
Mention the Android Studio-specific version which supports AGP 8.4.0
> docs: Update specific Android Studio version in README.md

- README.md
- lib/commands/animation.js
- package.json
https://github.com/appium/appium-espresso-driver/pull/1007/files#r1615504451
> feat: use adb settings method to set animation for newer than api level 26

- app/build.gradle
According to upadte sdk assistance, this does not have any diffs we must update
> feat: bump compileSdk and targetSdkVersion to 32

- README.md
- app/src/main/java/io/appium/settings/location/LocationBuilder.java
added support for mock location accuracy. 
issue #111
> feat: Add accuracy to the location builder

- app/src/main/java/io/appium/settings/location/LocationBuilder.java
Closes https://github.com/appium/io.appium.settings/issues/217
> fix: accuracy handling

- app/src/main/java/io/appium/settings/handlers/LocaleSettingHandler.java
- app/src/main/java/io/appium/settings/receivers/LocaleSettingReceiver.java
- lib/client.js
- lib/commands/locale.js
Related to https://github.com/appium/io.appium.settings/issues/221
> chore: Retry setting locale once to make sure hidden API policies were picked up

- README.md
- gradlew.bat
- lib/client.js
- lib/commands/bluetooth.js
- lib/commands/clipboard.js
- lib/commands/media-projection.js
- lib/commands/notifications.js
> chore: fix typos
