appium/io.appium.settings

AndroidManifest.xml, src/io/appium/settings/LocationService.java, src/io/appium/settings/MockLocationProvider.java
* This commit addresses the issue [appium #4309] (https://github.com/appium/appium/issues/4309)
* The code changes include the usage of `android.location.LocationManager` to add the ability to mock the location on device.
* Added service with the name `LocationService` that will be invoked from appium node server. [(appium PR)] (https://github.com/appium/appium/pull/6094)
=> adding mock location support to settings apk

app/build.gradle, app/src/main/java/io/appium/settings/LocationService.java
We anyway don't need this verification, since the app is always built in debug mode only and it seems like it does not always work as expected. See https://github.com/appium/appium/issues/8164#issuecomment-291500029 for the reference
=> Remove unnecessary verification for location service

README.md, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/io/appium/settings/handlers/LocaleSettingHandler.java, app/src/main/java/io/appium/settings/receivers/LocaleSettingReceiver.java
We can change the device's locale with the following commands:
```
$ adb shell pm grant io.appium.settings android.permission.CHANGE_CONFIGURATION
$ adb shell am broadcast -a io.appium.settings.locale --es LANG ja --es COUNTRY JP
```
We can change the device locale for Android O, N and the below.
So, we can avoid the crash like [Change locale cause appium to crash in Android N and O](https://github.com/appium/appium/issues/9619) if we change the locale with this feature.
=> implement locale setting handler

README.md, app/src/main/AndroidManifest.xml, app/src/main/java/io/appium/settings/AppiumIME.java, app/src/main/res/xml/method.xml
This will help to generate IME actions for UIA frameworks, where we cannot retrieve the actual view instance for the target element
=> Add an input service for IME actions generation

.gitignore, .npmignore, package.json
This will allow to save ~100 MB (!) while publishing the package to npm
=> Update .npmignore to exclude the unnecessary stuff

gulpfile.js, package.json
There is no transpilation in this package, so no need for any babel stuff. This will reduce the builds from Greenkeeper, too.
=> Remove babel dep

app/src/main/java/io/appium/settings/ForegroundService.java, app/src/main/java/io/appium/settings/LocationService.java, app/src/main/java/io/appium/settings/Settings.java
Fixing crash when trying to set the location on Pie emulator
Adb command 
```bash
adb shell am start-foreground-service --user 0 -n io.appium.settings/.LocationService --es longitude -87.12733 --es latitude 15.13697
```
Crash log
```
--------- beginning of crash
08-07 11:16:02.437 E/AndroidRuntime( 6577): FATAL EXCEPTION: main
08-07 11:16:02.437 E/AndroidRuntime( 6577): Process: io.appium.settings, PID: 6577
08-07 11:16:02.437 E/AndroidRuntime( 6577): android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
08-07 11:16:02.437 E/AndroidRuntime( 6577):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1775)
08-07 11:16:02.437 E/AndroidRuntime( 6577):     at android.os.Handler.dispatchMessage(Handler.java:105)
08-07 …
```
=> fixing app crash on location change

README.md, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/io/appium/settings/Settings.java, app/src/main/java/io/appium/settings/receivers/ClipboardReceiver.java
The next step would be to change ADB to set Appium Settings as default IME before getting the clipboard content for Android Q+
See https://github.com/appium/appium/issues/13466 for more details
=> feat: Add a broadcast service to receive the clipboard content

.travis.yml
No need to test on Node 8, and _all_ Travis VMs already have `nvm` installed.
=> build: adjust travis build

app/src/main/java/io/appium/settings/LocationTracker.java
In "LocationTracker.java" this block of code isn't entirely accurate:
```java
//noinspection deprecation
LocationServices.FusedLocationApi
.requestLocationUpdates(mGoogleApiClient, locationRequest, this);
Log.d(TAG, "Google Play Services location provider is connected");
```
`requestLocationUpdates` returns a `PendingResult<Status>` which is asynchronous, so `Google Play Services location provider is connected` isn't true until after the `PendingResult` has resolved. 
This is a problem if `LocationServices.FusedLocationApi.getLastLocation(mGoogleApiClient);` is called _immediately_ after `requestLocationUpdates` because it won't be ready yet and it will return `null`. The logcat error is `No location to return for getLastLocation()` and calls to `/location` return errors.
This PR is a …
=> fix: Fall back to non-GPS location services when requestLocationUpdates returns null

app/src/main/java/io/appium/settings/Settings.java
Fixes appium/appium#13736 . Now tests on Xiaomi A1 phone start without problems.
Needs testing on other real devices.
=> Start foreground service by calling proper method

README.md, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/io/appium/settings/NLService.java, app/src/main/java/io/appium/settings/Settings.java, app/src/main/java/io/appium/settings/helpers/Utils.java, app/src/main/java/io/appium/settings/notifications/StoredNotification.java, app/src/main/java/io/appium/settings/notifications/StoredNotifications.java, app/src/main/java/io/appium/settings/receivers/NotificationsReceiver.java, app/src/main/java/io/appium/settings/receivers/UnpairBluetoothDevicesReceiver.java, build.gradle, gradle/wrapper/gradle-wrapper.properties
Sometimes it might be useful to automate a scenario in Android whether the app under test received push notifications and verify their content. The PR makes it possible, although it is necessary to manually allow Appium Settings the access to system notifications. I think this should not be too hard, since we never delete this app with Appium, but only upgrade it if necessary, which means the system settings for it stay untouched.
@KazuCocoa Could you please assist with testing on real devices?
=> feat: Add a possibility to listen to system notifications

README.md, app/src/main/java/io/appium/settings/ForegroundService.java, app/src/main/java/io/appium/settings/LocationService.java, app/src/main/java/io/appium/settings/helpers/NotificationHelpers.java, build.gradle
Changes were tested on:
* Pixel XL (Android 9)
* Samsung Galaxy S8 (8.0.0)
* Samsung Galaxy J7 (8.1.0)
* 
Fixes errors 
"android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()"
=> Fix gps spoofing on android 8

app/src/main/java/io/appium/settings/handlers/LocaleSettingHandler.java
https://github.com/appium/appium/issues/14334
https://stackoverflow.com/questions/31904627/android-change-entire-app-layout-directions-programmatically
https://github.com/mozilla-mobile/focus-android/blob/5ba3bc737e13dc359904dc639e342f397bd767a0/app/src/main/java/org/mozilla/focus/locale/LocaleManager.java#L238-L240
We already support over API Level 18
I could not find properties in `getprop` like locale if we used it as a test case..
```
kazu$ adb shell am broadcast -a io.appium.settings.locale --es lang fa --es country AF
Broadcasting: Intent { act=io.appium.settings.locale flg=0x400000 (has extras) }
Broadcast completed: result=0
kazu$ adb shell am broadcast -a io.appium.settings.locale --es lang ja --es country JP
Broadcasting: Intent { act=io.appium.settings.locale flg=0x400000 (has …
```
=> feat: apply config.setLayoutDirection to set RTL properly for the locale

app/src/main/java/io/appium/settings/LocationService.java
Hi there, 
Somehow for location service, intent can be null, so i got null pointer exception in LocationService:88. I share logcat file with you.
[device.log](https://github.com/appium/io.appium.settings/files/5318653/device.log)
=> Fix crash when intent is null

app/src/main/java/io/appium/settings/receivers/LocationInfoReceiver.java, build.gradle
This is needed to align the output with iOS, where 7 characters after the decimal separator are returned
=> chore: Increase geo coordinates preciseness

app/src/main/java/io/appium/settings/LocationService.java, app/src/main/java/io/appium/settings/location/LocationFactory.java
This is required in order to properly mock location updates for applications that require valid speed.
Setting location speed to 0.0 will make the location.hasSpeed() method to wrongly report that it has valid speed even though location.speed is 0.0 and in documentation this value is considered as invalid speed.
This was improved by enabling to set speed from exterior by sending "speed" parameter or if no speed was provided then the speed field will no longer be set making the location object to correctly report that it does not have speed.
This is related to:
- **python-client** pull request: https://github.com/appium/python-client/pull/594
- **appium-adb** pull request https://github.com/appium/appium-adb/pull/563
=> feat: Added optional speed parameter for proper location mocking

build.gradle
fix https://github.com/appium/io.appium.settings/issues/68
```
% npm install      
> io.appium.settings@4.0.2 prepare
> npm run build
> io.appium.settings@4.0.2 build
> ./gradlew clean assembleDebug && npm run move-apks
> Task :app:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
BUILD SUCCESSFUL in 37s
27 actionable tasks: 27 executed
> io.appium.settings@4.0.2 move-apks
> rm -rf apks && mkdir -p apks && cp app/build/outputs/apk/debug/settings_apk-debug.apk apks
up to date, audited 1560 packages in 46s
115 packages are looking for funding
run `npm fund` for details
29 vulnerabilities (13 moderate, 14 high, 2 critical)
```
I remember this repo still referred to jcenter.
=> fix: refer to mavenCentral instead of jcenter

app/build.gradle, app/src/main/java/io/appium/settings/receivers/LocaleSettingReceiver.java, build.gradle, gradle/wrapper/gradle-wrapper.properties
The way locale is set is hacky and since the built-in Locale class does not have any validation of the provided locale parameters we could potentially brick the device. This change adds basic validation of known locale names and avoids the private API to be called if the locale name is not known.
=> fix: Implement locale validation

README.md, app/src/main/AndroidManifest.xml, app/src/main/java/io/appium/settings/Settings.java, app/src/main/java/io/appium/settings/recorder/RecorderConstant.java, app/src/main/java/io/appium/settings/recorder/RecorderService.java, app/src/main/java/io/appium/settings/recorder/RecorderThread.java, app/src/main/java/io/appium/settings/recorder/RecorderUtil.java
…Android.Q
REQUIRED STEPS to activate screenrecord feature:
- adb shell pm grant io.appium.settings android.permission.RECORD_AUDIO
- adb shell appops set io.appium.settings PROJECT_MEDIA allow
TO START SCREENRECORD:
- adb shell am start -n "io.appium.settings/io.appium.settings.Settings" -a io.appium.settings.recording.ACTION_START --es filename abc.mp4
TO STOP SCREENRECORD:
- adb shell am start -n "io.appium.settings/io.appium.settings.Settings" -a io.appium.settings.recording.ACTION_STOP
TO PULL RECORDED MP4 FILE:
- adb pull /storage/emulated/0/Android/data/io.appium.settings/files/abc.mp4 abc.mp4
=> feat: Implement internal audio/video recording for devices >= Android Q

app/src/main/java/io/appium/settings/Settings.java
I don't see an actual need to wait for 1 second until the activity is closed. Also, this creates an unnecessary video frames where a white screen is shown for media projection recordings
=> chore: Reduce the finish activity delay to zero

.github/workflows/publish.js.yml
This repository does not upload npm modules, so devDependencies won't be in the package.
Also this repo has no tests via npm run test, so we can remove it from the push task.
=> ci: use node 16, cleanup a bit

package.json
I don't see much point into having sources in the published package. It only takes extra space and slows down the deployment
=> chore: Exclude sources from the published npm package

.releaserc, package.json
Current out release task only generates changelos in https://github.com/appium/io.appium.settings/releases, but it would be helpful to prepare a file which has changelos in it.
https://github.com/semantic-release/changelog#examples also recommend to tweak the order, so this PR follows the recommendation a bit.
Expected behavior by this is:
- CHANGELOG.md in the top will have all changelog (or newer than this version)
- the npm package will have it
If this works well, I'd like to add the same one in other drivers so that users can track changelogs with this generator (without our work to collect changes in one changelog)
=> chore: add changelog plugin to generate it automatically

.github/workflows/publish.js.yml
The action project is already archived. I thought I already removed that, but still exist. Let's remove the unused one
=> ci: remove Upload Release Asse

.releaserc, package.json
no module error occurred. Let me add the plugin via package.json as same as the git one
=> chore: fix the installation error in the @semantic-release/changelog

package.json
Reverts appium/io.appium.settings#102
> node-versions: node v18 is now the minimum required version of node. this is in line with our [node support policy](https://semantic-release.gitbook.io/semantic-release/support/node-support-policy). please see [our recommendations](https://semantic-release.gitbook.io/semantic-release/support/node-version#recommended-solution) for releasing with a different node version than your project normally uses, if necessary.
Noticed this point. Maybe we should add the build nodejs version update in the same change, so lets revert the change for now
=> Revert "chore(deps-dev): bump semantic-release from 19.0.5 to 20.0.2"

app/src/main/java/io/appium/settings/AppiumIME.java
Appium IME receives editor action commands by intercepting `onKeyDown` events, but it does not intercept the corresponding `onKeyUp` events. This results in extraneous `onKeyUp` events being sent to the application when performing editor actions through Appium.
This PR modifies the `onKeyUp` handler to suppress key up events while processing editor action commands, similarly to `onKeyDown`.
<details>
<summary>Test script</summary>
This script opens a key event test page and performs an editor action. Without the patch, extraneous key up events for the command string `/send/` will be visible on the page.
```
import time
from appium import webdriver
desired_caps = {
'platformName': 'Android',
'deviceName': 'Android Emulator',
'browserName': 'Chrome',
'automationName': 'UiAutomator2'
} …
```
=> fix: Prevent Appium IME from sending extraneous onKeyUp events

README.md, app/src/main/java/io/appium/settings/receivers/LocaleSettingReceiver.java
This PR provides the ability to change language locale to an unidentified language.
For us when we set a locale(unidentified by the Android OS) but a custom locale name(understood by the Android application) the app instead of showing the text, shows an ID which is mapped to a language translation database. This helps us to check whether the textual elements on the screen are mapped to the correct translation ID for each language the app supports.
This is how the Appium settings app behaves for unidentified locale without this PR's change
```bash
$ adb shell am broadcast -a io.appium.settings.locale -n io.appium.settings/.receivers.LocaleSettingReceiver --es lang xx --es country US
Broadcasting: Intent { act=io.appium.settings.locale flg=0x400000 …
```
=> feat: add option to ignore locale verification

app/src/main/AndroidManifest.xml, app/src/main/java/io/appium/settings/EmptyIME.java
It is convenient to not have keyboard popping up in order to run various tests. `EmptyIME` does exactly that - it allows input without showing the on-screen keyboard.
=> feat: Add EmptyIME

README.md, app/build.gradle, app/src/main/java/io/appium/settings/LocationTracker.java, app/src/main/java/io/appium/settings/location/FusedLocationProvider.java
With the latest location service, `asGoogleApiClient` was removed.
According to the https://developers.google.com/android/guides/api-client 
> These objects automatically manage the connection to Google Play services. When a connection is available, each API client object executes requests in order. Otherwise, the client object queues the requests
So... maybe we no longer need them...?
I have tested below command worked expectedly with Google map on a real device.
> adb shell am start-foreground-service --user 0 -n io.appium.settings/.LocationService --es longitude "10.0000" --es latitude "10.0000"
>  adb shell am stopservice io.appium.settings/.LocationService
I have installed the settings app with `-g` option.
---
Let me ask https://github.com/appium/appium/issues/19238 if this helps …
=> feat: use play services location 21

.eslintignore, .github/workflows/build.yml, .github/workflows/unit-test.yml, .mocharc.js, index.js, lib/client.js, lib/commands/animation.js, lib/commands/clipboard.js, lib/commands/geolocation.js, lib/commands/locale.js, lib/commands/media.js, lib/commands/network.js, lib/commands/notifications.js, lib/commands/sms.js, lib/commands/typing.js, lib/commands/utf7.js, lib/constants.js, lib/logger.js, package.json, test/unit/json-parsing-specs.js, tsconfig.json
The next step would be to switch clients to use calls from this module rather than appium-adb.
Eventually the duplicated stuff will be deprecated and cut-off from the latter, so this module would be the only owner of the functionality related to it.
=> feat: Add javascript wrappers over Settings App APIs

package.json
Reverts appium/io.appium.settings#164
=> fix: Revert "chore(deps-dev): bump conventional-changelog-conventionalcommits from 7.0.2 to 8.0.0"

app/build.gradle, gradle.properties
Enable BuildConfig generation in module-level build.gradle
this property is deprecated in Android Gradle Plugin (AGP) 8.0 and is scheduled to be removed in AGP 9.0.
=> chore: Enable BuildConfig generation

app/build.gradle, app/src/main/java/io/appium/settings/LocationService.java, app/src/main/java/io/appium/settings/handlers/AnimationSettingHandler.java, app/src/main/java/io/appium/settings/recorder/RecorderThread.java
- Updated createLocationManagerMockProvider method to use getProviderProperties for API level 31 and above.
- Added runtime API level checks to ensure backward compatibility with API levels below 31.
- Removed dependency on LocationProvider in the calling method.
- Handled null cases for provider name and provider properties.
- Ensured compatibility and adherence to modern Android best practices.
=> refactor: LocationManager provider

README.md
Closes https://github.com/appium/io.appium.settings/issues/180
=> docs: address hidden api policy

lib/client.js
```
lib/client.js:139:16 - error TS2555: Expected at least 2 arguments, but got 1.
139       this.log.debug(output);
~~~~~
node_modules/@appium/logger/build/lib/types.d.ts:28:27
28     debug(prefix: string, message: any, ...args: any[]): void;
~~~~~~~~~~~~
An argument for 'message' was not provided.
```
=> fix: log argument

app/src/main/java/io/appium/settings/recorder/RecorderThread.java
Running long and/or large test suites with screen recording for each test sometimes fails on screen recording start/stop: the media projection used for screen recording is never stopped, so after running for about an hour, the appium settings app must be killed before the screen recording starts working again. 
This can also be reproduced by running a single test with screen recoding, then leaving the device idle for a while (notice that screen recording status bar icon never disappears) and then running the test again.
Call `mediaProjection.stop()` when screen recording is stopped. This makes sure that system resources are released and media projection is properly cleaned up.
=> fix: Stop media projection when stopping recording

app/src/main/java/io/appium/settings/ForegroundService.java, app/src/main/java/io/appium/settings/Settings.java, app/src/main/java/io/appium/settings/SettingsReceivers.java
The current method of registering broadcast receivers could keep adding the registration count. This causes https://github.com/appium/appium-uiautomator2-driver/issues/852 error:
> "message": "12-19 14:51:22.023 1664 1664 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{io.appium.settings/io.appium.settings.Settings}: java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 1664, callerPackage: io.appium.settings"
especially when a user calls the recording feature.
After learning Android implementation practice, I think the registration on a service creation would be more appropriate since we expect such services need to keep running in foreground to work properly.
e.g.
```
kazu $ adb shell am broadcast -a …
```
=> fix: Do not register the broad cast receivers for record action

app/src/main/AndroidManifest.xml
This PR fixes a crash that happened while trying to enabling/disabling bluetooth in devices with API level >= 31.
Just adding the missing `BLUETOOTH_CONNECT` permission fixes the issue. I added also `BLUETOOTH_SCAN` to enable future use cases for starting Bluetooth scans (not sure if will ever be used).
<details>
<summary>Stack trace</summary>
```
FATAL EXCEPTION: main
Process: io.appium.settings, PID: 18440
java.lang.RuntimeException: Error receiving broadcast Intent { act=io.appium.settings.bluetooth flg=0x400010 (has extras) } in io.appium.settings.receivers.BluetoothConnectionSettingReceiver@f2d9c69
at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1818)
at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$mcNAAl1SQ4MyJPyDg8TJ2x2h0Rk(Unknown …
```
=> fix: crash while enabling/disabling bluetooth on API level >= 31
